ccflags-y += -Idrivers/media/platform/msm/camera_v2-land-land
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land-land/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-land-land/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_ispif.o
